### ISSUE TITLE
Meta: Documentation

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#339]
At the moment, our documentation contains very little information besides the bare definitions and specifications. To improve the entropy of our docu, we should improve this with informative docstrings of the following format:
```
"""[Summary]

:param [ParamName]: [ParamDescription], defaults to [DefaultParamVal]
:type [ParamName]: [ParamType](, optional)
...
:raises [ErrorType]: [ErrorDescription]
...
:return: [ReturnDescription]
:rtype: [ReturnType]
"""
```
Whenever it makes sense, we can add links to the official Django docu or copy small parts of it.

After adding the docstrings, we also have to execute the `dev-tools/generate_documentation.sh` to add the changes to the html files.

- [x] #231 Automatically generate documentation
- [x] #324 Improve documentation of forms
- [x] #325 Improve documentation of cms models
- [x] #326 Improve documentation of views
- [x] #327 Improve documentation of templatetags
- [x] #328 Improve documentation of tests
- [x] #329 Improve documentation of cms utils
- [x] #330 Improve documentation of cms apps (CmsConfig)
- [x] #331 Improve documentation of view decorators
- [x] #332 Improve documentation of cms page xliff converter
- [x] #333 Improve documentation of cms rules
- [x] #334 Improve documentation of cms urls
- [x] #335 Improve documentation of cms constants
- [x] #336 Improve documentation of backend package
- [x] #337 Improve documentation of api
- [x] #338 Improve documentation of gvz_api package
- [x] #351 Improve readability of documentation
- [x] #375 Automated doc updates
- [ ] #421 Check docstrings for correctness
- [x] #408 Move wiki and readme to documentation
- [x] #422 Add contribution guide to documentation
- [ ] #427 Add CircleCI documentation
- [x] #453 Add page about sphinx to documentation
